openapi: 3.0.1
info:
  title: The AIS Subscription Endpoint
  version: 1.0.0
paths:
  /ais-subscription:
    get:
      description: List all the subscriptions for notifications (up to 100), ordered
        by last update descending (Limit and sorting to be implemented)
      operationId: getAis-subscription
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NotificationSubscription'
    post:
      description: Set up Notification Subscriptions for AIS Messages
      operationId: postAis-subscription
      requestBody:
        description: The Subscription to register
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationSubscription'
            example:
              listenerUrl: http://a.b.c/p1/p2
              stream: VESSEL_INFO
              action: Subscribe
              timeOfSubscription: '2019-11-14T11:03:54Z'
              imos:
              - 12334
              - 234234
        required: true
      responses:
        '200':
          description: Subscription successfully Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        default:
          description: An error occurred while updating the description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rejected'
components:
  schemas:
    NotificationSubscription:
      required:
      - listenerUrl
      - stream
      - timeOfSubscription
      type: object
      properties:
        listenerUrl:
          type: string
        stream:
          type: string
        timeOfSubscription:
          type: string
          format: date-time
        action:
          type: string
        imos:
          type: array
          items:
            type: integer
        lid:
          type: string
    Rejected:
      required:
      - subscription
      - reason
      type: object
      properties:
        subscription:
          $ref: '#/components/schemas/NotificationSubscription'
        reason:
          type: string
    Success:
      required:
      - subscription
      type: object
      properties:
        subscription:
          $ref: '#/components/schemas/NotificationSubscription'
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Crux-Systems/tst2/1.0.0
